[workspace]
resolver = "3"
members = ["elytra-mock","elytra-wasm","elytra-conf", "elytra-cli", "bytepack"]


package.license = "MIT"
package.homepage = "https://github.com/piksel/mbconf"
package.repository = "https://github.com/piksel/mbconf"
package.readme = "README.md"
