name: Deployment
on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths:
      - ".github/workflows/web.yml"
      - "docs/src/**.md"
      - "docs/book.toml"
      - "elytra-web/*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Install mdBook
      #   run: |
      #     curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
      #     rustup update
      #     cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build docs
        run: |
          mkdir -p elytra-web/public/docs
          mdbook build --dest-dir elytra-web/public/docs docs

      - name: Build web
        run: |
          cd elytra-web
          npm install
          npm run build

      - name: Archive dist
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      actions: write
      checks: write
      contents: write
    steps:
      - name: Checkout web branch
        uses: actions/checkout@v4
        with:
          ref: 'web'

      - name: Download dist
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist

      - name: Copy book to web
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Deploy web"
          git push